Load Numpy

In [ ]:
import numpy as np

The Basics

In [5]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [7]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
# Get dimension
b.ndim

2

In [12]:
# Get shape
b.shape

(2, 3)

In [14]:
# Get size
b.itemsize

8

In [17]:
# Get total size
b.nbytes

48

Accessing/changing specific elements, rows, columns, etc

In [18]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
# Get a specific element [r, c]
a[1, 5]

13